import { Router } from 'express';
import { HealthController } from '../controllers/health.controller';
import taskRoutes from './task.routes';
import authRoutes from './auth.routes';
import userRoutes from './user.routes';
import projectRoutes from './project.routes';
import commentRoutes from './comment.routes';
import subtaskRoutes from './subtask.routes';
import metricsRoutes from './metrics.routes';
import searchRoutes from './search.routes';
import analysisRoutes from './analysis.routes';
import testingRoutes from './testing.routes';
import performanceRoutes from './performance.routes';
import securityRoutes from './security.routes';
import { apiLimiter } from '../middleware/rate-limit.middleware';
import { AdminController } from '../controllers/admin.controller';
import { authenticate, authorize } from '../middleware/auth.middleware';
import { UserRole } from '../types';
import workflowRuleRoutes from './workflow-rule.routes';
const router = Router();

router.get('/', HealthController.getRoot);
router.get('/health', HealthController.getHealth);
router.get('/admin/jobs', authenticate, authorize(UserRole.ADMIN), AdminController.getJobsStatus);
router.use(apiLimiter);

router.use('/tasks', taskRoutes);
router.use('/workflow/rules', workflowRuleRoutes);
router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/projects', projectRoutes);
router.use('/comments', commentRoutes);
router.use('/subtasks', subtaskRoutes);
router.use('/search', searchRoutes);
router.use('/analysis', analysisRoutes);
router.use('/testing', testingRoutes);
router.use('/performance', performanceRoutes);
router.use('/security', securityRoutes);
router.use('/', metricsRoutes);

export default router;